#!/bin/bash -x
#$ -S /bin/bash
#$ -l h_rt=12:00:00
#$ -l h_vmem=12G
#$ -q all.q
#$ -wd /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_runs/070119/CNN/scripts

echo "Load python"
# conda environment with required Python packages:
# numpy
# logging

source activate channel-maker

# which sample is considered
echo ${SAMPLEARG}

python "data_import/training_set_OC_by_sample.py" \
	--sample ${SAMPLEARG}
