cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.memGB}G
    --job-name={wildcards.sample}-{rule}-smk
    --time={resources.time}
    --output=logs/{rule}/{rule}-{wildcards.sample}-%j.out
    --error=logs/{rule}/{rule}-{wildcards.sample}-%j.err
default-resources:
  - memGB=8
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: False
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True


#jobs: 50
#cluster: slurm # sbatch -t {resources.time} --mem={resources.memGB}G -c 1 --error logs/sm.slurm.%j.$N.{rule}.err --output logs/sm.slurm.%j.$N.{rule}.out"
#use-conda: true
#use-singularity: false
#latency-wait: 240
#restart-times: 3
#keep-going: false
#rerun-incomplete: true
