bam_dir: "/hpc/compgen/projects/googling-the-cancer-genome/sv-channels/analysis/SPIDER/1KG/BAM/"
out_dir: "svchan"
fasta: "/hpc/compgen/projects/googling-the-cancer-genome/sv-channels/analysis/SPIDER/1KG/reference/GRCh38_full_analysis_set_plus_decoy_hla.fa"
bedpe_dir: "/hpc/compgen/projects/googling-the-cancer-genome/sv-channels/analysis/SPIDER/1KG/sv-channels-data/"
truth_bedpe_dir: "/hpc/compgen/projects/googling-the-cancer-genome/sv-channels/analysis/SPIDER/1KG/truth-sets/1KG/"
svchan_dir: "/hpc/compgen/users/bpedersen/src/sv-channels/"
