#!/bin/bash -x
#$ -S /bin/bash
#$ -l h_rt=12:00:00
#$ -l h_vmem=12G
#$ -q all.q
#$ -wd /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_runs/060219/CNN/scripts

echo "Load python"
# conda environment with required Python packages:
# pysam
# numpy
# pickle
# bz2file
# logging
source activate channel-maker

python "genome_wide/labels.py" \
    --sample ${SAMPLEARG} \
    --window ${WINDOWARG} \
    --logfile ${SAMPLEARG}"_labels_"${WINDOWARG}".log"

