---
channels:
  - anaconda
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - snakemake
  - intervaltree
  - pysam
  - matplotlib
  - numpy
  - pandas
  - bz2file
  - twobitreader
  - scikit-learn
  - tensorflow>=2.0.0
  - r-base
  - r-argparser
  - bioconductor-structuralvariantannotation=1.6
  - xenon-cli
  - jq
  - cigar
  - coreutils
  - samtools
  - ucsc-bedgraphtobigwig
  - ucsc-fatotwobit
  - seqkit
  - scikit-optimize
  - pyfaidx
  - zarr
  - pyvcf
