#!/bin/bash -x
#$ -S /bin/bash
#$ -l h_rt=24:00:00
#$ -l h_vmem=64G
#$ -q all.q
#$ -wd /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_runs/060219/CNN/scripts/model/data

echo "Load python"
# conda environment with required Python packages:
# pysam
# numpy
# pickle
# bz2file
# logging
source activate channel-maker

python ${PRGARG}".py" \
	--sample ${SAMPLEARG} \
	--outputpath ${OUTARG} \
	--logfile ${PRGARG}"_"${MODEARG}".log" \
	--window ${WINDOWARG} \
	--mode ${MODEARG} \
	--bam ${BAMARG} \
	--save_npz True
