#!/bin/bash -x
#$ -S /bin/bash
#$ -l h_rt=24:00:00
#$ -l h_vmem=128G
#$ -q all.q
#$ -wd /hpc/cog_bioinf/ridder/users/lsantuari/Git/DeepSV_runs/060219/CNN/scripts/model/tier1

echo "Load python"
# conda environment with required Python packages:
# pysam
# numpy
# pickle
# bz2file
# logging

conda activate mcfly

python ${PRGARG}".py" \
    --sample ${SAMPLE_ARG} \
    --chromosome  ${CHRARG} \
    --channeldir ${CHANNELDIRARG} \
    --window ${WINARG} \
    --outputpath ${OUTDIRARG} \
    --model ${MODELARG}
